# Site settings
title: CS Women UMass Amherst
email: womenchairs@cs.umass.edu
description: Promoting and supporting the representation and interests of women in computing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cics.umass.edu/~women"
twitter_username: CSWomenUMass
github_username: cswomenumass
grad_cochairs: "Emma Tosch, Emma Strubell"
ugrad_cochairs: "Cassian Corey, Supriya Kankure"

gems:
  - jekyll-mentions

# Build settings
markdown: kramdown
paginate: 5
posts: _posts/blog-posts

# Blog magic
authors:
  tosch:
    display_name: Emma Tosch
    gravatar: df6572b0616ed24c7efbfe9b5daeb2af
    email: etosch@cs.umass.edu
    web: http://cics.umass.edu/~etosch
    twitter: emmatosch
    github: etosch
  myungha:
   display_name: Myung-ha Jang
   web: http://cics.umass.edu/~mhjang
  strubell:
   display_name: Emma Strubell
   web: http://cics.umass.edu/~strubell
  sofya:
    display_name: Sofya Vorotnikova
    web: http://cics.umass.edu/~svorotni

# Recognized pages
navigation:
- text: About
  url: /about.html
- text: Positions	
  url: /positions.html
- text: Blog
  url: /index.html
- text: Events
  url: /events.html
- text: Resources
  url: /resources.html
- text: Publicity
  url: /publicity.html
- text: Get Involved!
  url: /getinvolved.html

# Collections
collections:
  - positions
