# Site settings
title: CS Women UMass Amherst
email: womenchairs@cs.umass.edu
description: Promoting and supporting the representation and interests of women in computing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cics.umass.edu/~women"
twitter_username: CSWomenUMass
github_username: cswomenumass
grad_cochairs: "Nidhi Mundra, Manpreet Kaur, Neha Yadav"
ugrad_cochairs: "Supriya Kankure, Diane Tam"

gems:
  - jekyll-mentions
  - jekyll-paginate

# Build settings
markdown: kramdown
paginate: 5
posts: _posts/blog-posts

# Blog magic
authors:
  tosch:
    display_name: Emma Tosch
    gravatar: df6572b0616ed24c7efbfe9b5daeb2af
    email: etosch@cs.umass.edu
    web: http://cics.umass.edu/~etosch
    twitter: emmatosch
    github: etosch
  myungha:
   display_name: Myung-ha Jang
   web: http://cics.umass.edu/~mhjang
  strubell:
   display_name: Emma Strubell
   web: http://cics.umass.edu/~strubell
  sofya:
    display_name: Sofya Vorotnikova
    web: http://cics.umass.edu/~svorotni
  shiri:
    display_name: Shiri Dori-Hacohen
    web: http://cics.umass.edu/~shiri
  jfoley:
    display_name: John Foley
    email: jfoley@cs.umass.edu
    web: http://cics.umass.edu/~jfoley
    twitter: johnfoleyiv
    github: jjfiv
  shamya:
    display_name: Shamya Karumbaiah
    email: shamya@cs.umass.edu
    web: http://cics.umass.edu/~shamya
  rian:
    display_name: Rian Shambaugh
    email: rian@cs.umass.edu
    web: http://cics.umass.edu/~rian
    github: rolivia
  nidhimundra:
    display_name: Nidhi Mundra
    email: nmundra@cs.umass.edu
    web: http://cics.umass.edu/~nmundra
    github: nidhimundra
  kritishrivastava:
    display_name: Kriti Shrivastava
    email: kshrivastava@cs.umass.edu
    web: https://www.linkedin.com/in/shrivastava-kriti/
    github: kritishrivastava


# Recognized pages
navigation:
- text: About
  url: /about.html
- text: Officers
  url: /officers.html
- text: Blog
  url: /index.html
- text: Events
  url: /events.html
- text: WW2A
  url: /WW2A.html
- text: Travel Grant
  url: /travelgrant.html
- text: Resources
  url: /resources.html
- text: Publicity
  url: /publicity.html
- text: Get Involved!
  url: /getinvolved.html

# Collections
collections:
  - positions
  - publicity
  - officers
  
