# Site
name: "UMass Amherst CS Women"
title: "UMass Amherst CS Women"
description: "Promoting the representation and interests of women in computing. "
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
mailchimp-list: 
include: ["_pages", "_officers"]
permalink: /:title/

# Authors
authors:
  cswomen:
    name: CS Women
    display_name: CSWomen
    email: cswomenleadership@gmail.com
    avatar: '/assets/images/avatars/cswomen.png'
    twitter: https://twitter.com/cswomenumass
  jfoley:
    avatar: '/assets/images/avatars/jfoley.png'
    display_name: Jfoley
  tosch:
    avatar: '/assets/images/avatars/etosch.png'
    display_name: Emma Tosch
  kritishrivastava:
    avatar: '/assets/images/avatars/kritishrivastava.png'
    display_name: Kriti Shrivastava
  manpreet:
    avatar: '/assets/images/avatars/manpreet.png'
    display_name: Manpreet
  myungha:
    avatar: '/assets/images/avatars/myungha.png'
    display_name: Myungha Jang
  nidhimundra:
    avatar: '/assets/images/avatars/nidhimundra.png'
    display_name: Nidhi Mundra
  rian:
    avatar: '/assets/images/avatars/rian.png'
    display_name: Rian Shambaugh
  shamya:
    avatar: '/assets/images/avatars/S.png'
    display_name: Shamya
  shiri:
    avatar: '/assets/images/avatars/S.png'
    display_name: Shiri
  sofya:
    avatar: '/assets/images/avatars/S.png'
    display_name: Sofya
    
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 3
paginate_path: "blog/page:num"
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

collections:
  - officers
